### ISSUE TITLE
Feature request: Multiple mobs trades

### ISSUE THREAD

**Issue by KahpotVanilla** [Reldeam/CustomVillagerTrades#10]
Like the title says, Custom trades with all mobs and animals besides Villagers

**Comment by Reldeam** [comment]
While this is a great idea, it does require me to bypass the Spigot API and hit the Minecraft API directly. This issue with this is that the plugin will most likely break each time Minecraft updates and I will have to update the plugin. I am not able to guarantee support in such a manner. I want to ensure that this plugin will last a long time, so I'm going to have to close this ticket for now. If you have any more good ideas in the future, please don't hesitate to ask :)
